### ISSUE TITLE
not able to register agents with agentverse

### ISSUE THREAD

**Issue by abhifetch** [fetchai/fetchai#42]
Initially my agent was working fine. But as soon as i deleted my agent on agentverse and tried to re-register it.
Script gives below error

`(venv) abhi@Fetchs-MacBook-Pro langgraph storm agent % python3 storm_agent.py
2024-12-27 10:32:23,036 - fetchai - INFO - Registering with Almanac API
2024-12-27 10:32:23,543 - __main__ - ERROR - Error initializing agent: 422 Client Error: Unprocessable Entity for url: https://agentverse.ai/v1/agents
Traceback (most recent call last):
  File "/Users/abhi/Desktop/langgraph fetchai/langgraph storm agent/storm_agent.py", line 87, in <module>
    init_agent()
    ~~~~~~~~~~^^
  File "/Users/abhi/Desktop/langgraph fetchai/langgraph storm agent/storm_agent.py", line 58, in init_agent
    register_with_agentverse(
    ~~~~~~~~~~~~~~~~~~~~~~~~^
        identity=wiki_identity,
        ^^^^^^^^^^^^^^^^^^^^^^^
    ...<18 lines>...
        """
        ^^^
    )
    ^
  File "/Users/abhi/Desktop/langgraph fetchai/langgraph storm agent/venv/lib/python3.13/site-packages/fetchai/registration.py", line 148, in register_with_agentverse
    r.raise_for_status()
    ~~~~~~~~~~~~~~~~~~^^
  File "/Users/abhi/Desktop/langgraph fetchai/langgraph storm agent/venv/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://agentverse.ai/v1/agents
(venv) abhi@Fetchs-MacBook-Pro langgraph storm agent % `



I belive with latest version of uagents we dont have to provide seed phrase anymore and this might be the root cause for this. but still could you please have a look into this?

**Comment by bleib1dj** [comment]
@abhifetch this should be resolved, we're registering and reregistering thousands of agents a day but if you see this happening still please let me know.
